#!/usr/bin/env python3
"""
Ingenuity Node – Updated (Sentience 5.5 compliant)

Agreements applied:
- ROS-optional (runs fully without ROS)
- Async-first where useful
- No hidden global state
- Clear lifecycle: generate → validate → integrate → persist → execute
- Evolver-compatible (can be called by evolver.py)
- Deterministic, auditable behavior (no self-modifying runtime exec beyond sandbox)
"""

from __future__ import annotations

import ast
import asyncio
import logging
import sys
import types
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional, Callable

# ---------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(name)s | %(levelname)s | %(message)s",
    stream=sys.stdout,
)
logger = logging.getLogger("Ingenuity_Node")

# ---------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------
@dataclass
class NodeArtifact:
    node_name: str
    code: str
    module: Optional[types.ModuleType] = None
    instance: Optional[Any] = None
    file_path: Optional[Path] = None


# ---------------------------------------------------------------------
# Ingenuity Node
# ---------------------------------------------------------------------
class IngenuityNode:
    """
    Responsible for safe creation, validation, integration and execution
    of new nodes. Acts as a *tooling node*, not a cognitive one.
    """

    def __init__(
        self,
        workspace: Path | str = "./ingenuity_nodes",
        notifier: Optional[Callable[[Dict[str, Any]], None]] = None,
    ):
        self.workspace = Path(workspace)
        self.workspace.mkdir(parents=True, exist_ok=True)

        self.nodes: Dict[str, NodeArtifact] = {}
        self.notifier = notifier or self._default_notifier

        logger.info("IngenuityNode initialized at %s", self.workspace)

    # -----------------------------------------------------------------
    # Core API (used by evolver.py)
    # -----------------------------------------------------------------
    def generate_node_code(self, node_name: str, specification: str) -> str:
        """
        Deterministic scaffold. Evolver or LLM can override upstream.
        """
        return f'''\
class {node_name}:
    """
    Auto-generated by IngenuityNode.
    Specification:
    {specification}
    """

    def __init__(self):
        self.node_name = "{node_name}"

    def run(self):
        print("[{node_name}] running – {specification}")
'''

    def validate_code(self, code: str) -> bool:
        try:
            ast.parse(code)
            return True
        except SyntaxError as e:
            self.notifier({
                "event": "validation_failed",
                "error": str(e),
            })
            return False

    def integrate_node(self, node_name: str, code: str) -> Optional[Any]:
        """
        Loads code into a sandboxed module namespace.
        """
        if not self.validate_code(code):
            return None

        module = types.ModuleType(node_name)

        try:
            exec(code, module.__dict__)
            cls = getattr(module, node_name)
            instance = cls()

            self.nodes[node_name] = NodeArtifact(
                node_name=node_name,
                code=code,
                module=module,
                instance=instance,
            )

            self.notifier({
                "event": "node_integrated",
                "node": node_name,
            })

            return instance

        except Exception as e:
            self.notifier({
                "event": "integration_error",
                "node": node_name,
                "error": str(e),
            })
            logger.exception("Integration failed")
            return None

    async def save_node_code(self, node_name: str, code: str) -> Path:
        """
        Async disk persistence.
        """
        node_dir = self.workspace / node_name
        node_dir.mkdir(parents=True, exist_ok=True)

        path = node_dir / f"{node_name}.py"
        loop = asyncio.get_running_loop()
        await loop.run_in_executor(None, path.write_text, code)

        artifact = self.nodes.get(node_name)
        if artifact:
            artifact.file_path = path

        self.notifier({
            "event": "node_saved",
            "node": node_name,
            "path": str(path),
        })

        return path

    async def create_and_deploy_node(
        self,
        node_name: str,
        specification: str,
    ) -> Optional[Any]:
        code = self.generate_node_code(node_name, specification)
        await self.save_node_code(node_name, code)
        return self.integrate_node(node_name, code)

    def run_node(self, node_name: str) -> None:
        artifact = self.nodes.get(node_name)

        if not artifact or not artifact.instance:
            logger.error("Node %s not available", node_name)
            return

        try:
            artifact.instance.run()
            self.notifier({
                "event": "node_executed",
                "node": node_name,
            })
        except Exception as e:
            logger.error("Execution error in %s: %s", node_name, e)

    # -----------------------------------------------------------------
    # Utilities
    # -----------------------------------------------------------------
    def list_nodes(self) -> Dict[str, str]:
        return {
            name: str(art.file_path) if art.file_path else "memory-only"
            for name, art in self.nodes.items()
        }

    def _default_notifier(self, msg: Dict[str, Any]) -> None:
        logger.info("EVENT: %s", msg)


# ---------------------------------------------------------------------
# Standalone CLI (optional)
# ---------------------------------------------------------------------
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Ingenuity Node (updated)")
    parser.add_argument("--workspace", type=str, default="./ingenuity_nodes")
    parser.add_argument("--generate", metavar="NAME|SPEC", help="Generate + run node")

    args = parser.parse_args()

    async def main():
        node = IngenuityNode(workspace=args.workspace)
        if args.generate:
            name, spec = args.generate.split("|", 1)
            await node.create_and_deploy_node(name, spec)
            node.run_node(name)

    asyncio.run(main())
